// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/jmgilman/headjack/internal/keychain"
)

// Ensure, that KeychainMock does implement keychain.Keychain.
// If this is not the case, regenerate this file with moq.
var _ keychain.Keychain = &KeychainMock{}

// KeychainMock is a mock implementation of keychain.Keychain.
//
//	func TestSomethingThatUsesKeychain(t *testing.T) {
//
//		// make and configure a mocked keychain.Keychain
//		mockedKeychain := &KeychainMock{
//			DeleteFunc: func(account string) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(account string) (string, error) {
//				panic("mock out the Get method")
//			},
//			SetFunc: func(account string, secret string) error {
//				panic("mock out the Set method")
//			},
//		}
//
//		// use mockedKeychain in code that requires keychain.Keychain
//		// and then make assertions.
//
//	}
type KeychainMock struct {
	// DeleteFunc mocks the Delete method.
	DeleteFunc func(account string) error

	// GetFunc mocks the Get method.
	GetFunc func(account string) (string, error)

	// SetFunc mocks the Set method.
	SetFunc func(account string, secret string) error

	// calls tracks calls to the methods.
	calls struct {
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Account is the account argument value.
			Account string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Account is the account argument value.
			Account string
		}
		// Set holds details about calls to the Set method.
		Set []struct {
			// Account is the account argument value.
			Account string
			// Secret is the secret argument value.
			Secret string
		}
	}
	lockDelete sync.RWMutex
	lockGet    sync.RWMutex
	lockSet    sync.RWMutex
}

// Delete calls DeleteFunc.
func (mock *KeychainMock) Delete(account string) error {
	if mock.DeleteFunc == nil {
		panic("KeychainMock.DeleteFunc: method is nil but Keychain.Delete was just called")
	}
	callInfo := struct {
		Account string
	}{
		Account: account,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(account)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedKeychain.DeleteCalls())
func (mock *KeychainMock) DeleteCalls() []struct {
	Account string
} {
	var calls []struct {
		Account string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *KeychainMock) Get(account string) (string, error) {
	if mock.GetFunc == nil {
		panic("KeychainMock.GetFunc: method is nil but Keychain.Get was just called")
	}
	callInfo := struct {
		Account string
	}{
		Account: account,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(account)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedKeychain.GetCalls())
func (mock *KeychainMock) GetCalls() []struct {
	Account string
} {
	var calls []struct {
		Account string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Set calls SetFunc.
func (mock *KeychainMock) Set(account string, secret string) error {
	if mock.SetFunc == nil {
		panic("KeychainMock.SetFunc: method is nil but Keychain.Set was just called")
	}
	callInfo := struct {
		Account string
		Secret  string
	}{
		Account: account,
		Secret:  secret,
	}
	mock.lockSet.Lock()
	mock.calls.Set = append(mock.calls.Set, callInfo)
	mock.lockSet.Unlock()
	return mock.SetFunc(account, secret)
}

// SetCalls gets all the calls that were made to Set.
// Check the length with:
//
//	len(mockedKeychain.SetCalls())
func (mock *KeychainMock) SetCalls() []struct {
	Account string
	Secret  string
} {
	var calls []struct {
		Account string
		Secret  string
	}
	mock.lockSet.RLock()
	calls = mock.calls.Set
	mock.lockSet.RUnlock()
	return calls
}
