// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/jmgilman/headjack/internal/auth"
)

// Ensure, that ProviderMock does implement auth.Provider.
// If this is not the case, regenerate this file with moq.
var _ auth.Provider = &ProviderMock{}

// ProviderMock is a mock implementation of auth.Provider.
//
//	func TestSomethingThatUsesProvider(t *testing.T) {
//
//		// make and configure a mocked auth.Provider
//		mockedProvider := &ProviderMock{
//			AuthenticateFunc: func(ctx context.Context, storage auth.Storage) error {
//				panic("mock out the Authenticate method")
//			},
//			GetFunc: func(storage auth.Storage) (string, error) {
//				panic("mock out the Get method")
//			},
//		}
//
//		// use mockedProvider in code that requires auth.Provider
//		// and then make assertions.
//
//	}
type ProviderMock struct {
	// AuthenticateFunc mocks the Authenticate method.
	AuthenticateFunc func(ctx context.Context, storage auth.Storage) error

	// GetFunc mocks the Get method.
	GetFunc func(storage auth.Storage) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Authenticate holds details about calls to the Authenticate method.
		Authenticate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Storage is the storage argument value.
			Storage auth.Storage
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Storage is the storage argument value.
			Storage auth.Storage
		}
	}
	lockAuthenticate sync.RWMutex
	lockGet          sync.RWMutex
}

// Authenticate calls AuthenticateFunc.
func (mock *ProviderMock) Authenticate(ctx context.Context, storage auth.Storage) error {
	if mock.AuthenticateFunc == nil {
		panic("ProviderMock.AuthenticateFunc: method is nil but Provider.Authenticate was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Storage auth.Storage
	}{
		Ctx:     ctx,
		Storage: storage,
	}
	mock.lockAuthenticate.Lock()
	mock.calls.Authenticate = append(mock.calls.Authenticate, callInfo)
	mock.lockAuthenticate.Unlock()
	return mock.AuthenticateFunc(ctx, storage)
}

// AuthenticateCalls gets all the calls that were made to Authenticate.
// Check the length with:
//
//	len(mockedProvider.AuthenticateCalls())
func (mock *ProviderMock) AuthenticateCalls() []struct {
	Ctx     context.Context
	Storage auth.Storage
} {
	var calls []struct {
		Ctx     context.Context
		Storage auth.Storage
	}
	mock.lockAuthenticate.RLock()
	calls = mock.calls.Authenticate
	mock.lockAuthenticate.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *ProviderMock) Get(storage auth.Storage) (string, error) {
	if mock.GetFunc == nil {
		panic("ProviderMock.GetFunc: method is nil but Provider.Get was just called")
	}
	callInfo := struct {
		Storage auth.Storage
	}{
		Storage: storage,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(storage)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedProvider.GetCalls())
func (mock *ProviderMock) GetCalls() []struct {
	Storage auth.Storage
} {
	var calls []struct {
		Storage auth.Storage
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}
