# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

builds:
  - id: darwin
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/jmgilman/headjack/internal/version.Version={{.Version}}
      - -X github.com/jmgilman/headjack/internal/version.Commit={{.Commit}}
      - -X github.com/jmgilman/headjack/internal/version.Date={{.Date}}
    binary: hjk

  - id: linux
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/jmgilman/headjack/internal/version.Version={{.Version}}
      - -X github.com/jmgilman/headjack/internal/version.Commit={{.Commit}}
      - -X github.com/jmgilman/headjack/internal/version.Date={{.Date}}
    binary: hjk

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: GilmanLab
    name: headjack
  name_template: "CLI {{ .Version }}"
  draft: false
  prerelease: auto

homebrew_casks:
  - repository:
      owner: GilmanLab
      name: tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Casks
    name: headjack
    binaries:
      - hjk
    homepage: "https://headjack.gilman.io"
    description: "CLI tool for spawning isolated LLM coding agents in container environments"
    commit_msg_template: "Brew cask update for {{ .ProjectName }} version {{ .Tag }}"
    skip_upload: auto
    ids:
      - darwin
    caveats: |
      Headjack requires a container runtime (Podman, Docker).
      Get started: hjk auth claude && hjk run feat/my-feature --agent claude "Your task"
