// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/jmgilman/headjack/internal/git"
)

// Ensure, that OpenerMock does implement git.Opener.
// If this is not the case, regenerate this file with moq.
var _ git.Opener = &OpenerMock{}

// OpenerMock is a mock implementation of git.Opener.
//
//	func TestSomethingThatUsesOpener(t *testing.T) {
//
//		// make and configure a mocked git.Opener
//		mockedOpener := &OpenerMock{
//			OpenFunc: func(ctx context.Context, path string) (git.Repository, error) {
//				panic("mock out the Open method")
//			},
//		}
//
//		// use mockedOpener in code that requires git.Opener
//		// and then make assertions.
//
//	}
type OpenerMock struct {
	// OpenFunc mocks the Open method.
	OpenFunc func(ctx context.Context, path string) (git.Repository, error)

	// calls tracks calls to the methods.
	calls struct {
		// Open holds details about calls to the Open method.
		Open []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Path is the path argument value.
			Path string
		}
	}
	lockOpen sync.RWMutex
}

// Open calls OpenFunc.
func (mock *OpenerMock) Open(ctx context.Context, path string) (git.Repository, error) {
	if mock.OpenFunc == nil {
		panic("OpenerMock.OpenFunc: method is nil but Opener.Open was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Path string
	}{
		Ctx:  ctx,
		Path: path,
	}
	mock.lockOpen.Lock()
	mock.calls.Open = append(mock.calls.Open, callInfo)
	mock.lockOpen.Unlock()
	return mock.OpenFunc(ctx, path)
}

// OpenCalls gets all the calls that were made to Open.
// Check the length with:
//
//	len(mockedOpener.OpenCalls())
func (mock *OpenerMock) OpenCalls() []struct {
	Ctx  context.Context
	Path string
} {
	var calls []struct {
		Ctx  context.Context
		Path string
	}
	mock.lockOpen.RLock()
	calls = mock.calls.Open
	mock.lockOpen.RUnlock()
	return calls
}
