// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/jmgilman/headjack/internal/registry"
)

// Ensure, that ClientMock does implement registry.Client.
// If this is not the case, regenerate this file with moq.
var _ registry.Client = &ClientMock{}

// ClientMock is a mock implementation of registry.Client.
//
//	func TestSomethingThatUsesClient(t *testing.T) {
//
//		// make and configure a mocked registry.Client
//		mockedClient := &ClientMock{
//			GetMetadataFunc: func(ctx context.Context, ref string) (*registry.ImageMetadata, error) {
//				panic("mock out the GetMetadata method")
//			},
//		}
//
//		// use mockedClient in code that requires registry.Client
//		// and then make assertions.
//
//	}
type ClientMock struct {
	// GetMetadataFunc mocks the GetMetadata method.
	GetMetadataFunc func(ctx context.Context, ref string) (*registry.ImageMetadata, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetMetadata holds details about calls to the GetMetadata method.
		GetMetadata []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref string
		}
	}
	lockGetMetadata sync.RWMutex
}

// GetMetadata calls GetMetadataFunc.
func (mock *ClientMock) GetMetadata(ctx context.Context, ref string) (*registry.ImageMetadata, error) {
	if mock.GetMetadataFunc == nil {
		panic("ClientMock.GetMetadataFunc: method is nil but Client.GetMetadata was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Ref string
	}{
		Ctx: ctx,
		Ref: ref,
	}
	mock.lockGetMetadata.Lock()
	mock.calls.GetMetadata = append(mock.calls.GetMetadata, callInfo)
	mock.lockGetMetadata.Unlock()
	return mock.GetMetadataFunc(ctx, ref)
}

// GetMetadataCalls gets all the calls that were made to GetMetadata.
// Check the length with:
//
//	len(mockedClient.GetMetadataCalls())
func (mock *ClientMock) GetMetadataCalls() []struct {
	Ctx context.Context
	Ref string
} {
	var calls []struct {
		Ctx context.Context
		Ref string
	}
	mock.lockGetMetadata.RLock()
	calls = mock.calls.GetMetadata
	mock.lockGetMetadata.RUnlock()
	return calls
}
