// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/jmgilman/headjack/internal/exec"
)

// Ensure, that ExecutorMock does implement exec.Executor.
// If this is not the case, regenerate this file with moq.
var _ exec.Executor = &ExecutorMock{}

// ExecutorMock is a mock implementation of exec.Executor.
//
//	func TestSomethingThatUsesExecutor(t *testing.T) {
//
//		// make and configure a mocked exec.Executor
//		mockedExecutor := &ExecutorMock{
//			LookPathFunc: func(name string) (string, error) {
//				panic("mock out the LookPath method")
//			},
//			RunFunc: func(ctx context.Context, opts *exec.RunOptions) (*exec.Result, error) {
//				panic("mock out the Run method")
//			},
//		}
//
//		// use mockedExecutor in code that requires exec.Executor
//		// and then make assertions.
//
//	}
type ExecutorMock struct {
	// LookPathFunc mocks the LookPath method.
	LookPathFunc func(name string) (string, error)

	// RunFunc mocks the Run method.
	RunFunc func(ctx context.Context, opts *exec.RunOptions) (*exec.Result, error)

	// calls tracks calls to the methods.
	calls struct {
		// LookPath holds details about calls to the LookPath method.
		LookPath []struct {
			// Name is the name argument value.
			Name string
		}
		// Run holds details about calls to the Run method.
		Run []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Opts is the opts argument value.
			Opts *exec.RunOptions
		}
	}
	lockLookPath sync.RWMutex
	lockRun      sync.RWMutex
}

// LookPath calls LookPathFunc.
func (mock *ExecutorMock) LookPath(name string) (string, error) {
	if mock.LookPathFunc == nil {
		panic("ExecutorMock.LookPathFunc: method is nil but Executor.LookPath was just called")
	}
	callInfo := struct {
		Name string
	}{
		Name: name,
	}
	mock.lockLookPath.Lock()
	mock.calls.LookPath = append(mock.calls.LookPath, callInfo)
	mock.lockLookPath.Unlock()
	return mock.LookPathFunc(name)
}

// LookPathCalls gets all the calls that were made to LookPath.
// Check the length with:
//
//	len(mockedExecutor.LookPathCalls())
func (mock *ExecutorMock) LookPathCalls() []struct {
	Name string
} {
	var calls []struct {
		Name string
	}
	mock.lockLookPath.RLock()
	calls = mock.calls.LookPath
	mock.lockLookPath.RUnlock()
	return calls
}

// Run calls RunFunc.
func (mock *ExecutorMock) Run(ctx context.Context, opts *exec.RunOptions) (*exec.Result, error) {
	if mock.RunFunc == nil {
		panic("ExecutorMock.RunFunc: method is nil but Executor.Run was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Opts *exec.RunOptions
	}{
		Ctx:  ctx,
		Opts: opts,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	return mock.RunFunc(ctx, opts)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//
//	len(mockedExecutor.RunCalls())
func (mock *ExecutorMock) RunCalls() []struct {
	Ctx  context.Context
	Opts *exec.RunOptions
} {
	var calls []struct {
		Ctx  context.Context
		Opts *exec.RunOptions
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}
